import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.scss";
import ProgressBar from "@/app/_components/ProgressBar";
import HeroSection from "@/app/_components/ui/HeroSection/HeroSection";
import AnimatedCursor from "@/app/_components/cursor/AnimatedCursor";
import Footer from "@/app/_components/ui/Footer/Footer";
import Navbar from "@/app/_components/ui/Navbar/Navbar";


const geistSans = localFont({
  src: "../assets//fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative text-white antialiased`}>
        <ProgressBar/>
        <AnimatedCursor/>

        <main className={'min-h-screen relative mx-auto px-6 sm:px-12 lg:max-w-[70rem] xl:max-w-[76rem] 2xl:max-w-[92rem]'}>
          <Navbar/>
          <HeroSection/>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
